version: '3'

services:
  web:
    build:
      context: .
      args:
        - S3_ACCESS_KEY=${S3_ACCESS_KEY}
        - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
        - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    container_name: s3_container
    ports:
      - 8000:8000
    restart: always
